### ISSUE TITLE
Update SEVIRI calibration

### ISSUE THREAD

**Issue by sfinkens** [foua-pps/level1c4pps#18]
Update SEVIRI calibration to use JF's new coefficients: http://msgcpp.knmi.nl/mediawiki/index.php/MSG-SEVIRI_solar_channel_calibration

**Comment by ninahakansson** [comment]
Does the updated calibration effect also older satellites? Meteosat9 (2010) and Meteosat11 (2015)?

**Comment by sfinkens** [comment]
@ninahakansson The slopes for Meteosat-11 change, older satellites are not affected

**Comment by ninahakansson** [comment]
That is good news!

**Comment by sfinkens** [comment]
Jan-Fokke updated the intercalibration again, so we should synchronize.

**Comment by ninahakansson** [comment]
Ok!
