### ISSUE TITLE
Update MSG-4 calibration coefficients

### ISSUE THREAD

**Issue by sfinkens** [foua-pps/level1c4pps#47]
MSG-4 calibration coefficients need a final update for CLAAS-3. From JFM:

```
S=21.040+0.2877e-3*day_2000 (ch1),
S=24.966+0.6074e-3*day_2000 (ch2),
S=21.236+0.1420e-3*day_2000 (ch3).
```

**Comment by sfinkens** [comment]
Since I will be looking at `level1c4pps` regarding SEVIRI Native format, I can also do that.

**Comment by ninahakansson** [comment]
Thanks @sfinkens!

**Comment by kgkarl** [comment]
I must check this with you: Is this update really valid for all SEVIRI instruments? What I heard from Jan Fokke was that he had a new correction for MSG4 and not for all MSGs.

**Comment by sfinkens** [comment]
You're right @kgkarl , this is for MSG-4 only. Sorry, the issue title and description were misleading.
