### ISSUE TITLE
Satpy doesn't support Python 3.8 anymore

### ISSUE THREAD

**Issue by pnuu** [foua-pps/level1c4pps#79]
I think python 3.8 isn't supported in satpy anymore...

_Originally posted by @mraspaud in https://github.com/foua-pps/level1c4pps/issues/78#issuecomment-1517373674_

**Comment by pnuu** [comment]
Just to amend the above short quote: the CI tests need to be adjusted. If Python 3.8 support is still needed, an old version of Satpy will be needed for that case. In general Satpy officially supports only the last 3 stable Python versions (3.9, 3.10 and 3.11 at the moment).

**Comment by ninahakansson** [comment]
Thanks for reporting @pnuu! I think we can just skip python 3.8 support.

**Comment by ninahakansson** [comment]
Latest release of PPS supports python 3.12 so skipping 3.8 is now for sure fine.
